{
 "title": "Snallabot Prod Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Madden", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Exports",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(madden_exports_total{job=\"snallabot-prod\"}[1m]) * 60",
     "legendFormat": "{{export_type}}"
    }
   ]
  },
  {
   "title": "Averag Number of Events per Madden Export",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(madden_events_size_distribution_sum[5m]) / rate(madden_events_size_distribution_count[5m])",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  { "title": "Discord", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Rate of Discord Slash Commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(discord_commands_total{command_type=\"SLASH\"}[1m])",
     "legendFormat": "{{command_name}} {{command_type}}"
    }
   ]
  },
  {
   "title": "Rate of Discord Message Components",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(discord_commands_total{command_type=\"MESSAGE_COMPONENT\"}[2m])",
     "legendFormat": "{{command_name}} {{command_type}}"
    }
   ]
  },
  {
   "title": "Rate of Discord Message Components",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(discord_commands_total{command_type=\"AUTOCOMPLETE\"}[2m])",
     "legendFormat": "{{command_name}} {{command_type}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "View Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(view_cache_hits_total{}[1m]) / rate(view_cache_requests_total{}[1m])",
     "legendFormat": "{{view_id}}"
    }
   ]
  },
  {
   "title": "Madden Hash Cache HIt Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 27 },
   "targets": [
    {
     "expr": "rate(madden_hash_cache_hits_total[1m]) / rate(madden_hash_cache_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "View Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(view_cache_size_bytes_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Madden Hash Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(madden_hash_cache_size_bytes_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}