// Mechanically generated field<->column mappings, verified 1:1 against madden_league_types.ts
// and the live schema (sql/madden_schema.sql) - every column below resolved to exactly one
// TS field via normalized-name matching (strip non-alphanumerics, lowercase), including the
// irregular casing fields (bCVRating, qBStyleTrait, dLBullRushTrait, etc.) that a naive
// camelCase-to-snake_case converter would have mangled. Excludes each table's own primary
// key columns (handled explicitly per-table in madden_postgres.ts, not via this generic list)
// and league_id/platform/updated_at (handled specially on every table) plus
// signature_abilities (JSONB, needs JSON.stringify - see PLAYER_JSON_COLUMNS below).

export type ColumnMapping = { column: string, field: string, pgType: string }

export const TEAM_COLUMNS: ColumnMapping[] = [
  { column: "ovr_rating", field: "ovrRating", pgType: "smallint[]" },
  { column: "injury_count", field: "injuryCount", pgType: "smallint[]" },
  { column: "div_name", field: "divName", pgType: "text[]" },
  { column: "city_name", field: "cityName", pgType: "text[]" },
  { column: "logo_id", field: "logoId", pgType: "integer[]" },
  { column: "abbr_name", field: "abbrName", pgType: "text[]" },
  { column: "user_name", field: "userName", pgType: "text[]" },
  { column: "nick_name", field: "nickName", pgType: "text[]" },
  { column: "off_scheme", field: "offScheme", pgType: "smallint[]" },
  { column: "secondary_color", field: "secondaryColor", pgType: "integer[]" },
  { column: "primary_color", field: "primaryColor", pgType: "integer[]" },
  { column: "def_scheme", field: "defScheme", pgType: "smallint[]" },
  { column: "display_name", field: "displayName", pgType: "text[]" },
]

export const STANDING_COLUMNS: ColumnMapping[] = [
  { column: "season_index", field: "seasonIndex", pgType: "smallint[]" },
  { column: "week_index", field: "weekIndex", pgType: "smallint[]" },
  { column: "stage_index", field: "stageIndex", pgType: "smallint[]" },
  { column: "calendar_year", field: "calendarYear", pgType: "smallint[]" },
  { column: "rank", field: "rank", pgType: "smallint[]" },
  { column: "prev_rank", field: "prevRank", pgType: "smallint[]" },
  { column: "seed", field: "seed", pgType: "smallint[]" },
  { column: "division_id", field: "divisionId", pgType: "smallint[]" },
  { column: "division_name", field: "divisionName", pgType: "text[]" },
  { column: "conference_id", field: "conferenceId", pgType: "smallint[]" },
  { column: "conference_name", field: "conferenceName", pgType: "text[]" },
  { column: "playoff_status", field: "playoffStatus", pgType: "smallint[]" },
  { column: "team_name", field: "teamName", pgType: "text[]" },
  { column: "team_ovr", field: "teamOvr", pgType: "smallint[]" },
  { column: "total_wins", field: "totalWins", pgType: "smallint[]" },
  { column: "total_losses", field: "totalLosses", pgType: "smallint[]" },
  { column: "total_ties", field: "totalTies", pgType: "smallint[]" },
  { column: "home_wins", field: "homeWins", pgType: "smallint[]" },
  { column: "home_losses", field: "homeLosses", pgType: "smallint[]" },
  { column: "home_ties", field: "homeTies", pgType: "smallint[]" },
  { column: "away_wins", field: "awayWins", pgType: "smallint[]" },
  { column: "away_losses", field: "awayLosses", pgType: "smallint[]" },
  { column: "away_ties", field: "awayTies", pgType: "smallint[]" },
  { column: "div_wins", field: "divWins", pgType: "smallint[]" },
  { column: "div_losses", field: "divLosses", pgType: "smallint[]" },
  { column: "div_ties", field: "divTies", pgType: "smallint[]" },
  { column: "conf_wins", field: "confWins", pgType: "smallint[]" },
  { column: "conf_losses", field: "confLosses", pgType: "smallint[]" },
  { column: "conf_ties", field: "confTies", pgType: "smallint[]" },
  { column: "win_pct", field: "winPct", pgType: "real[]" },
  { column: "win_loss_streak", field: "winLossStreak", pgType: "smallint[]" },
  { column: "pts_for", field: "ptsFor", pgType: "integer[]" },
  { column: "pts_for_rank", field: "ptsForRank", pgType: "smallint[]" },
  { column: "pts_against", field: "ptsAgainst", pgType: "integer[]" },
  { column: "pts_against_rank", field: "ptsAgainstRank", pgType: "smallint[]" },
  { column: "net_pts", field: "netPts", pgType: "integer[]" },
  { column: "off_total_yds", field: "offTotalYds", pgType: "integer[]" },
  { column: "off_total_yds_rank", field: "offTotalYdsRank", pgType: "smallint[]" },
  { column: "off_pass_yds", field: "offPassYds", pgType: "integer[]" },
  { column: "off_pass_yds_rank", field: "offPassYdsRank", pgType: "smallint[]" },
  { column: "off_rush_yds", field: "offRushYds", pgType: "integer[]" },
  { column: "off_rush_yds_rank", field: "offRushYdsRank", pgType: "smallint[]" },
  { column: "def_total_yds", field: "defTotalYds", pgType: "integer[]" },
  { column: "def_total_yds_rank", field: "defTotalYdsRank", pgType: "smallint[]" },
  { column: "def_pass_yds", field: "defPassYds", pgType: "integer[]" },
  { column: "def_pass_yds_rank", field: "defPassYdsRank", pgType: "smallint[]" },
  { column: "def_rush_yds", field: "defRushYds", pgType: "integer[]" },
  { column: "def_rush_yds_rank", field: "defRushYdsRank", pgType: "smallint[]" },
  { column: "to_diff", field: "tODiff", pgType: "smallint[]" },
  { column: "cap_available", field: "capAvailable", pgType: "integer[]" },
  { column: "cap_room", field: "capRoom", pgType: "integer[]" },
  { column: "cap_spent", field: "capSpent", pgType: "integer[]" },
]

export const SCHEDULE_COLUMNS: ColumnMapping[] = [
  { column: "stage_index", field: "stageIndex", pgType: "smallint[]" },
  { column: "status", field: "status", pgType: "smallint[]" },
  { column: "home_team_id", field: "homeTeamId", pgType: "integer[]" },
  { column: "away_team_id", field: "awayTeamId", pgType: "integer[]" },
  { column: "home_score", field: "homeScore", pgType: "smallint[]" },
  { column: "away_score", field: "awayScore", pgType: "smallint[]" },
  { column: "is_game_of_the_week", field: "isGameOfTheWeek", pgType: "boolean[]" },
]

export const PUNTING_STAT_COLUMNS: ColumnMapping[] = [
  { column: "roster_id", field: "rosterId", pgType: "integer[]" },
  { column: "team_id", field: "teamId", pgType: "integer[]" },
  { column: "schedule_id", field: "scheduleId", pgType: "integer[]" },
  { column: "stage_index", field: "stageIndex", pgType: "smallint[]" },
  { column: "full_name", field: "fullName", pgType: "text[]" },
  { column: "punt_att", field: "puntAtt", pgType: "smallint[]" },
  { column: "punt_yds", field: "puntYds", pgType: "smallint[]" },
  { column: "punt_yds_per_att", field: "puntYdsPerAtt", pgType: "real[]" },
  { column: "punt_net_yds", field: "puntNetYds", pgType: "smallint[]" },
  { column: "punt_net_yds_per_att", field: "puntNetYdsPerAtt", pgType: "real[]" },
  { column: "punt_longest", field: "puntLongest", pgType: "smallint[]" },
  { column: "punts_in_20", field: "puntsIn20", pgType: "smallint[]" },
  { column: "punt_tbs", field: "puntTBs", pgType: "smallint[]" },
  { column: "punts_blocked", field: "puntsBlocked", pgType: "smallint[]" },
]

export const TEAM_STAT_COLUMNS: ColumnMapping[] = [
  { column: "team_id", field: "teamId", pgType: "integer[]" },
  { column: "schedule_id", field: "scheduleId", pgType: "integer[]" },
  { column: "stage_index", field: "stageIndex", pgType: "smallint[]" },
  { column: "seed", field: "seed", pgType: "smallint[]" },
  { column: "total_wins", field: "totalWins", pgType: "smallint[]" },
  { column: "total_losses", field: "totalLosses", pgType: "smallint[]" },
  { column: "total_ties", field: "totalTies", pgType: "smallint[]" },
  { column: "to_diff", field: "tODiff", pgType: "smallint[]" },
  { column: "to_takeaways", field: "tOTakeaways", pgType: "smallint[]" },
  { column: "to_giveaways", field: "tOGiveaways", pgType: "smallint[]" },
  { column: "penalties", field: "penalties", pgType: "smallint[]" },
  { column: "penalty_yds", field: "penaltyYds", pgType: "integer[]" },
  { column: "off_pts_per_game", field: "offPtsPerGame", pgType: "real[]" },
  { column: "off_total_yds", field: "offTotalYds", pgType: "integer[]" },
  { column: "off_total_yds_gained", field: "offTotalYdsGained", pgType: "integer[]" },
  { column: "off_pass_yds", field: "offPassYds", pgType: "integer[]" },
  { column: "off_rush_yds", field: "offRushYds", pgType: "integer[]" },
  { column: "off_rush_tds", field: "offRushTds", pgType: "smallint[]" },
  { column: "off_pass_tds", field: "offPassTDs", pgType: "smallint[]" },
  { column: "off_sacks", field: "offSacks", pgType: "smallint[]" },
  { column: "off_fum_lost", field: "offFumLost", pgType: "smallint[]" },
  { column: "off_ints_lost", field: "offIntsLost", pgType: "smallint[]" },
  { column: "off_1st_downs", field: "off1stDowns", pgType: "smallint[]" },
  { column: "off_3rd_down_att", field: "off3rdDownAtt", pgType: "smallint[]" },
  { column: "off_3rd_down_conv", field: "off3rdDownConv", pgType: "smallint[]" },
  { column: "off_3rd_down_conv_pct", field: "off3rdDownConvPct", pgType: "real[]" },
  { column: "off_4th_down_att", field: "off4thDownAtt", pgType: "smallint[]" },
  { column: "off_4th_down_conv", field: "off4thDownConv", pgType: "smallint[]" },
  { column: "off_4th_down_conv_pct", field: "off4thDownConvPct", pgType: "real[]" },
  { column: "off_2pt_att", field: "off2PtAtt", pgType: "smallint[]" },
  { column: "off_2pt_conv", field: "off2PtConv", pgType: "smallint[]" },
  { column: "off_2pt_conv_pct", field: "off2PtConvPct", pgType: "real[]" },
  { column: "off_red_zones", field: "offRedZones", pgType: "smallint[]" },
  { column: "off_red_zone_tds", field: "offRedZoneTDs", pgType: "smallint[]" },
  { column: "off_red_zone_fgs", field: "offRedZoneFGs", pgType: "smallint[]" },
  { column: "off_red_zone_pct", field: "offRedZonePct", pgType: "real[]" },
  { column: "def_pts_per_game", field: "defPtsPerGame", pgType: "real[]" },
  { column: "def_total_yds", field: "defTotalYds", pgType: "integer[]" },
  { column: "def_pass_yds", field: "defPassYds", pgType: "integer[]" },
  { column: "def_rush_yds", field: "defRushYds", pgType: "integer[]" },
  { column: "def_sacks", field: "defSacks", pgType: "smallint[]" },
  { column: "def_forced_fum", field: "defForcedFum", pgType: "smallint[]" },
  { column: "def_fum_rec", field: "defFumRec", pgType: "smallint[]" },
  { column: "def_ints_rec", field: "defIntsRec", pgType: "smallint[]" },
  { column: "def_red_zones", field: "defRedZones", pgType: "smallint[]" },
  { column: "def_red_zone_tds", field: "defRedZoneTDs", pgType: "smallint[]" },
  { column: "def_red_zone_fgs", field: "defRedZoneFGs", pgType: "smallint[]" },
  { column: "def_red_zone_pct", field: "defRedZonePct", pgType: "real[]" },
]

export const PASSING_STAT_COLUMNS: ColumnMapping[] = [
  { column: "roster_id", field: "rosterId", pgType: "integer[]" },
  { column: "team_id", field: "teamId", pgType: "integer[]" },
  { column: "schedule_id", field: "scheduleId", pgType: "integer[]" },
  { column: "stage_index", field: "stageIndex", pgType: "smallint[]" },
  { column: "full_name", field: "fullName", pgType: "text[]" },
  { column: "pass_att", field: "passAtt", pgType: "smallint[]" },
  { column: "pass_comp", field: "passComp", pgType: "smallint[]" },
  { column: "pass_comp_pct", field: "passCompPct", pgType: "real[]" },
  { column: "pass_yds", field: "passYds", pgType: "smallint[]" },
  { column: "pass_yds_per_att", field: "passYdsPerAtt", pgType: "real[]" },
  { column: "pass_yds_per_game", field: "passYdsPerGame", pgType: "real[]" },
  { column: "pass_tds", field: "passTDs", pgType: "smallint[]" },
  { column: "pass_ints", field: "passInts", pgType: "smallint[]" },
  { column: "pass_sacks", field: "passSacks", pgType: "smallint[]" },
  { column: "pass_longest", field: "passLongest", pgType: "smallint[]" },
  { column: "pass_pts", field: "passPts", pgType: "smallint[]" },
  { column: "passer_rating", field: "passerRating", pgType: "real[]" },
]

export const KICKING_STAT_COLUMNS: ColumnMapping[] = [
  { column: "roster_id", field: "rosterId", pgType: "integer[]" },
  { column: "team_id", field: "teamId", pgType: "integer[]" },
  { column: "schedule_id", field: "scheduleId", pgType: "integer[]" },
  { column: "stage_index", field: "stageIndex", pgType: "smallint[]" },
  { column: "full_name", field: "fullName", pgType: "text[]" },
  { column: "fg_att", field: "fGAtt", pgType: "smallint[]" },
  { column: "fg_made", field: "fGMade", pgType: "smallint[]" },
  { column: "fg_comp_pct", field: "fGCompPct", pgType: "real[]" },
  { column: "fg_longest", field: "fGLongest", pgType: "smallint[]" },
  { column: "fg_50_plus_att", field: "fG50PlusAtt", pgType: "smallint[]" },
  { column: "fg_50_plus_made", field: "fG50PlusMade", pgType: "smallint[]" },
  { column: "xp_att", field: "xPAtt", pgType: "smallint[]" },
  { column: "xp_made", field: "xPMade", pgType: "smallint[]" },
  { column: "xp_comp_pct", field: "xPCompPct", pgType: "real[]" },
  { column: "kickoff_att", field: "kickoffAtt", pgType: "smallint[]" },
  { column: "kickoff_tbs", field: "kickoffTBs", pgType: "smallint[]" },
  { column: "kick_pts", field: "kickPts", pgType: "smallint[]" },
]

export const RUSHING_STAT_COLUMNS: ColumnMapping[] = [
  { column: "roster_id", field: "rosterId", pgType: "integer[]" },
  { column: "team_id", field: "teamId", pgType: "integer[]" },
  { column: "schedule_id", field: "scheduleId", pgType: "integer[]" },
  { column: "stage_index", field: "stageIndex", pgType: "smallint[]" },
  { column: "full_name", field: "fullName", pgType: "text[]" },
  { column: "rush_att", field: "rushAtt", pgType: "smallint[]" },
  { column: "rush_yds", field: "rushYds", pgType: "smallint[]" },
  { column: "rush_yds_per_att", field: "rushYdsPerAtt", pgType: "real[]" },
  { column: "rush_yds_per_game", field: "rushYdsPerGame", pgType: "real[]" },
  { column: "rush_yds_after_contact", field: "rushYdsAfterContact", pgType: "smallint[]" },
  { column: "rush_tds", field: "rushTDs", pgType: "smallint[]" },
  { column: "rush_fum", field: "rushFum", pgType: "smallint[]" },
  { column: "rush_broken_tackles", field: "rushBrokenTackles", pgType: "smallint[]" },
  { column: "rush_20_plus_yds", field: "rush20PlusYds", pgType: "smallint[]" },
  { column: "rush_longest", field: "rushLongest", pgType: "smallint[]" },
  { column: "rush_to_pct", field: "rushToPct", pgType: "real[]" },
  { column: "rush_pts", field: "rushPts", pgType: "smallint[]" },
]

export const DEFENSIVE_STAT_COLUMNS: ColumnMapping[] = [
  { column: "roster_id", field: "rosterId", pgType: "integer[]" },
  { column: "team_id", field: "teamId", pgType: "integer[]" },
  { column: "schedule_id", field: "scheduleId", pgType: "integer[]" },
  { column: "stage_index", field: "stageIndex", pgType: "smallint[]" },
  { column: "full_name", field: "fullName", pgType: "text[]" },
  { column: "def_total_tackles", field: "defTotalTackles", pgType: "smallint[]" },
  { column: "def_sacks", field: "defSacks", pgType: "real[]" },
  { column: "def_ints", field: "defInts", pgType: "smallint[]" },
  { column: "def_int_return_yds", field: "defIntReturnYds", pgType: "smallint[]" },
  { column: "def_deflections", field: "defDeflections", pgType: "smallint[]" },
  { column: "def_catch_allowed", field: "defCatchAllowed", pgType: "smallint[]" },
  { column: "def_forced_fum", field: "defForcedFum", pgType: "smallint[]" },
  { column: "def_fum_rec", field: "defFumRec", pgType: "smallint[]" },
  { column: "def_tds", field: "defTDs", pgType: "smallint[]" },
  { column: "def_safeties", field: "defSafeties", pgType: "smallint[]" },
  { column: "def_pts", field: "defPts", pgType: "smallint[]" },
]

export const RECEIVING_STAT_COLUMNS: ColumnMapping[] = [
  { column: "roster_id", field: "rosterId", pgType: "integer[]" },
  { column: "team_id", field: "teamId", pgType: "integer[]" },
  { column: "schedule_id", field: "scheduleId", pgType: "integer[]" },
  { column: "stage_index", field: "stageIndex", pgType: "smallint[]" },
  { column: "full_name", field: "fullName", pgType: "text[]" },
  { column: "rec_catches", field: "recCatches", pgType: "smallint[]" },
  { column: "rec_catch_pct", field: "recCatchPct", pgType: "real[]" },
  { column: "rec_drops", field: "recDrops", pgType: "smallint[]" },
  { column: "rec_yds", field: "recYds", pgType: "smallint[]" },
  { column: "rec_yds_per_catch", field: "recYdsPerCatch", pgType: "real[]" },
  { column: "rec_yds_per_game", field: "recYdsPerGame", pgType: "real[]" },
  { column: "rec_yds_after_catch", field: "recYdsAfterCatch", pgType: "smallint[]" },
  { column: "rec_yac_per_catch", field: "recYacPerCatch", pgType: "real[]" },
  { column: "rec_tds", field: "recTDs", pgType: "smallint[]" },
  { column: "rec_longest", field: "recLongest", pgType: "smallint[]" },
  { column: "rec_to_pct", field: "recToPct", pgType: "real[]" },
  { column: "rec_pts", field: "recPts", pgType: "smallint[]" },
]

export const PLAYER_COLUMNS: ColumnMapping[] = [
  { column: "roster_id", field: "rosterId", pgType: "integer[]" },
  { column: "team_id", field: "teamId", pgType: "integer[]" },
  { column: "first_name", field: "firstName", pgType: "text[]" },
  { column: "last_name", field: "lastName", pgType: "text[]" },
  { column: "position", field: "position", pgType: "text[]" },
  { column: "jersey_num", field: "jerseyNum", pgType: "smallint[]" },
  { column: "age", field: "age", pgType: "smallint[]" },
  { column: "height", field: "height", pgType: "smallint[]" },
  { column: "weight", field: "weight", pgType: "smallint[]" },
  { column: "college", field: "college", pgType: "text[]" },
  { column: "home_town", field: "homeTown", pgType: "text[]" },
  { column: "home_state", field: "homeState", pgType: "smallint[]" },
  { column: "years_pro", field: "yearsPro", pgType: "smallint[]" },
  { column: "rookie_year", field: "rookieYear", pgType: "smallint[]" },
  { column: "draft_round", field: "draftRound", pgType: "smallint[]" },
  { column: "draft_pick", field: "draftPick", pgType: "smallint[]" },
  { column: "is_free_agent", field: "isFreeAgent", pgType: "boolean[]" },
  { column: "is_active", field: "isActive", pgType: "boolean[]" },
  { column: "is_on_practice_squad", field: "isOnPracticeSquad", pgType: "boolean[]" },
  { column: "is_on_ir", field: "isOnIR", pgType: "boolean[]" },
  { column: "re_sign_status", field: "reSignStatus", pgType: "smallint[]" },
  { column: "dev_trait", field: "devTrait", pgType: "smallint[]" },
  { column: "scheme", field: "scheme", pgType: "smallint[]" },
  { column: "team_scheme_ovr", field: "teamSchemeOvr", pgType: "smallint[]" },
  { column: "player_scheme_ovr", field: "playerSchemeOvr", pgType: "smallint[]" },
  { column: "player_best_ovr", field: "playerBestOvr", pgType: "smallint[]" },
  { column: "legacy_score", field: "legacyScore", pgType: "integer[]" },
  { column: "experience_points", field: "experiencePoints", pgType: "integer[]" },
  { column: "skill_points", field: "skillPoints", pgType: "integer[]" },
  { column: "production_grade", field: "productionGrade", pgType: "real[]" },
  { column: "durability_grade", field: "durabilityGrade", pgType: "real[]" },
  { column: "physical_grade", field: "physicalGrade", pgType: "real[]" },
  { column: "intangible_grade", field: "intangibleGrade", pgType: "real[]" },
  { column: "size_grade", field: "sizeGrade", pgType: "real[]" },
  { column: "contract_salary", field: "contractSalary", pgType: "integer[]" },
  { column: "contract_bonus", field: "contractBonus", pgType: "integer[]" },
  { column: "contract_length", field: "contractLength", pgType: "smallint[]" },
  { column: "contract_years_left", field: "contractYearsLeft", pgType: "smallint[]" },
  { column: "cap_hit", field: "capHit", pgType: "integer[]" },
  { column: "cap_release_penalty", field: "capReleasePenalty", pgType: "integer[]" },
  { column: "cap_release_net_savings", field: "capReleaseNetSavings", pgType: "integer[]" },
  { column: "desired_salary", field: "desiredSalary", pgType: "integer[]" },
  { column: "desired_bonus", field: "desiredBonus", pgType: "integer[]" },
  { column: "desired_length", field: "desiredLength", pgType: "smallint[]" },
  { column: "injury_type", field: "injuryType", pgType: "smallint[]" },
  { column: "injury_length", field: "injuryLength", pgType: "smallint[]" },
  { column: "injury_rating", field: "injuryRating", pgType: "smallint[]" },
  { column: "run_style", field: "runStyle", pgType: "smallint[]" },
  { column: "aware_rating", field: "awareRating", pgType: "smallint[]" },
  { column: "speed_rating", field: "speedRating", pgType: "smallint[]" },
  { column: "accel_rating", field: "accelRating", pgType: "smallint[]" },
  { column: "agility_rating", field: "agilityRating", pgType: "smallint[]" },
  { column: "strength_rating", field: "strengthRating", pgType: "smallint[]" },
  { column: "stamina_rating", field: "staminaRating", pgType: "smallint[]" },
  { column: "tough_rating", field: "toughRating", pgType: "smallint[]" },
  { column: "jump_rating", field: "jumpRating", pgType: "smallint[]" },
  { column: "cit_rating", field: "cITRating", pgType: "smallint[]" },
  { column: "throw_power_rating", field: "throwPowerRating", pgType: "smallint[]" },
  { column: "throw_acc_rating", field: "throwAccRating", pgType: "smallint[]" },
  { column: "throw_acc_short_rating", field: "throwAccShortRating", pgType: "smallint[]" },
  { column: "throw_acc_mid_rating", field: "throwAccMidRating", pgType: "smallint[]" },
  { column: "throw_acc_deep_rating", field: "throwAccDeepRating", pgType: "smallint[]" },
  { column: "throw_on_run_rating", field: "throwOnRunRating", pgType: "smallint[]" },
  { column: "throw_under_pressure_rating", field: "throwUnderPressureRating", pgType: "smallint[]" },
  { column: "play_action_rating", field: "playActionRating", pgType: "smallint[]" },
  { column: "break_sack_rating", field: "breakSackRating", pgType: "smallint[]" },
  { column: "carry_rating", field: "carryRating", pgType: "smallint[]" },
  { column: "break_tackle_rating", field: "breakTackleRating", pgType: "smallint[]" },
  { column: "truck_rating", field: "truckRating", pgType: "smallint[]" },
  { column: "stiff_arm_rating", field: "stiffArmRating", pgType: "smallint[]" },
  { column: "spin_move_rating", field: "spinMoveRating", pgType: "smallint[]" },
  { column: "juke_move_rating", field: "jukeMoveRating", pgType: "smallint[]" },
  { column: "bcv_rating", field: "bCVRating", pgType: "smallint[]" },
  { column: "catch_rating", field: "catchRating", pgType: "smallint[]" },
  { column: "spec_catch_rating", field: "specCatchRating", pgType: "smallint[]" },
  { column: "route_run_short_rating", field: "routeRunShortRating", pgType: "smallint[]" },
  { column: "route_run_med_rating", field: "routeRunMedRating", pgType: "smallint[]" },
  { column: "route_run_deep_rating", field: "routeRunDeepRating", pgType: "smallint[]" },
  { column: "release_rating", field: "releaseRating", pgType: "smallint[]" },
  { column: "kick_power_rating", field: "kickPowerRating", pgType: "smallint[]" },
  { column: "kick_acc_rating", field: "kickAccRating", pgType: "smallint[]" },
  { column: "kick_ret_rating", field: "kickRetRating", pgType: "smallint[]" },
  { column: "pass_block_rating", field: "passBlockRating", pgType: "smallint[]" },
  { column: "pass_block_power_rating", field: "passBlockPowerRating", pgType: "smallint[]" },
  { column: "pass_block_finesse_rating", field: "passBlockFinesseRating", pgType: "smallint[]" },
  { column: "run_block_rating", field: "runBlockRating", pgType: "smallint[]" },
  { column: "run_block_power_rating", field: "runBlockPowerRating", pgType: "smallint[]" },
  { column: "run_block_finesse_rating", field: "runBlockFinesseRating", pgType: "smallint[]" },
  { column: "lead_block_rating", field: "leadBlockRating", pgType: "smallint[]" },
  { column: "impact_block_rating", field: "impactBlockRating", pgType: "smallint[]" },
  { column: "tackle_rating", field: "tackleRating", pgType: "smallint[]" },
  { column: "hit_power_rating", field: "hitPowerRating", pgType: "smallint[]" },
  { column: "pursuit_rating", field: "pursuitRating", pgType: "smallint[]" },
  { column: "play_rec_rating", field: "playRecRating", pgType: "smallint[]" },
  { column: "press_rating", field: "pressRating", pgType: "smallint[]" },
  { column: "man_cover_rating", field: "manCoverRating", pgType: "smallint[]" },
  { column: "zone_cover_rating", field: "zoneCoverRating", pgType: "smallint[]" },
  { column: "block_shed_rating", field: "blockShedRating", pgType: "smallint[]" },
  { column: "power_moves_rating", field: "powerMovesRating", pgType: "smallint[]" },
  { column: "finesse_moves_rating", field: "finesseMovesRating", pgType: "smallint[]" },
  { column: "change_of_direction_rating", field: "changeOfDirectionRating", pgType: "smallint[]" },
  { column: "long_snap_rating", field: "longSnapRating", pgType: "smallint[]" },
  { column: "sense_pressure_trait", field: "sensePressureTrait", pgType: "smallint[]" },
  { column: "penalty_trait", field: "penaltyTrait", pgType: "smallint[]" },
  { column: "play_ball_trait", field: "playBallTrait", pgType: "smallint[]" },
  { column: "cover_ball_trait", field: "coverBallTrait", pgType: "smallint[]" },
  { column: "qb_style_trait", field: "qBStyleTrait", pgType: "smallint[]" },
  { column: "lb_style_trait", field: "lBStyleTrait", pgType: "smallint[]" },
  { column: "big_hit_trait", field: "bigHitTrait", pgType: "boolean[]" },
  { column: "strip_ball_trait", field: "stripBallTrait", pgType: "boolean[]" },
  { column: "high_motor_trait", field: "highMotorTrait", pgType: "boolean[]" },
  { column: "clutch_trait", field: "clutchTrait", pgType: "boolean[]" },
  { column: "throw_away_trait", field: "throwAwayTrait", pgType: "boolean[]" },
  { column: "tight_spiral_trait", field: "tightSpiralTrait", pgType: "boolean[]" },
  { column: "fight_for_yards_trait", field: "fightForYardsTrait", pgType: "boolean[]" },
  { column: "predict_trait", field: "predictTrait", pgType: "boolean[]" },
  { column: "dl_swim_trait", field: "dLSwimTrait", pgType: "boolean[]" },
  { column: "dl_spin_trait", field: "dLSpinTrait", pgType: "boolean[]" },
  { column: "dl_bull_rush_trait", field: "dLBullRushTrait", pgType: "boolean[]" },
  { column: "feet_in_bounds_trait", field: "feetInBoundsTrait", pgType: "boolean[]" },
  { column: "pos_catch_trait", field: "posCatchTrait", pgType: "boolean[]" },
  { column: "hp_catch_trait", field: "hPCatchTrait", pgType: "boolean[]" },
  { column: "drop_open_pass_trait", field: "dropOpenPassTrait", pgType: "boolean[]" },
  { column: "yac_catch_trait", field: "yACCatchTrait", pgType: "boolean[]" },
]

// signature_abilities is JSONB (deliberate JSON exception, see sql/madden_schema.sql) -
// stores player.signatureSlotList verbatim, not mapped through ColumnMapping since it needs
// JSON.stringify rather than a plain value copy.
export const PLAYER_JSON_COLUMNS: ColumnMapping[] = [
  { column: "signature_abilities", field: "signatureSlotList", pgType: "jsonb[]" },
]
